AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: An example serverless API written in Golang.

Resources:
  ApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: go1.x
      Handler: api
      Timeout: 10
      Events:
        CatchAllHandler:
          Type: Api
          Properties:
            RestApiId: ApiGatewayApi
            Path: /{proxy+}
            Method: ANY
      Policies:
        - AmazonS3FullAccess
  
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowMethods: "'POST, GET, PUT'"
        AllowOrigin: "'*'"
  
  ConfigLambdaPermission:
    Type: "AWS::Lambda::Permission"
    DependsOn:
    - ApiGatewayApi
    - ApiFunction
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref ApiFunction
      Principal: apigateway.amazonaws.com
  
  S3EventHandler:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: go1.x
      Handler: s3_event_handler
      Timeout: 10

Outputs:
  Endpoint:
    Value: !Sub "https://${ApiGatewayApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
