AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: An example serverless API written in Golang.

Resources:

  Api:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: go1.x
      Handler: api
      Timeout: 10
      Events:
        RootHandler:
          Type: Api
          Properties:
            Path: '/'
            Method: get
        MessageHandler:
          Type: Api
          Properties:
            Path: '/message'
            Method: get
        HelloHandler:
          Type: Api
          Properties:
            Path: '/job'
            Method: post

Outputs:
  Endpoint:
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
